"""
ISIC Rev.5 — full division list + keyword mapping used by the classifier.
"""

ISIC_DIVISIONS = [
    ("01","Crop and animal production, hunting and related service activities","A","Agriculture, Forestry and Fishing"),
    ("02","Forestry and logging","A","Agriculture, Forestry and Fishing"),
    ("03","Fishing and aquaculture","A","Agriculture, Forestry and Fishing"),
    ("05","Mining of coal and lignite","B","Mining and Quarrying"),
    ("06","Extraction of crude petroleum and natural gas","B","Mining and Quarrying"),
    ("07","Mining of metal ores","B","Mining and Quarrying"),
    ("08","Other mining and quarrying","B","Mining and Quarrying"),
    ("09","Mining support service activities","B","Mining and Quarrying"),
    ("10","Manufacture of food products","C","Manufacturing"),
    ("11","Manufacture of beverages","C","Manufacturing"),
    ("12","Manufacture of tobacco products","C","Manufacturing"),
    ("13","Manufacture of textiles","C","Manufacturing"),
    ("14","Manufacture of wearing apparel","C","Manufacturing"),
    ("15","Manufacture of leather and related products","C","Manufacturing"),
    ("16","Manufacture of wood products","C","Manufacturing"),
    ("17","Manufacture of paper and paper products","C","Manufacturing"),
    ("18","Printing and reproduction of recorded media","C","Manufacturing"),
    ("19","Manufacture of coke and refined petroleum products","C","Manufacturing"),
    ("20","Manufacture of chemicals and chemical products","C","Manufacturing"),
    ("21","Manufacture of pharmaceutical products","C","Manufacturing"),
    ("22","Manufacture of rubber and plastics products","C","Manufacturing"),
    ("23","Manufacture of non-metallic mineral products","C","Manufacturing"),
    ("24","Manufacture of basic metals","C","Manufacturing"),
    ("25","Manufacture of fabricated metal products","C","Manufacturing"),
    ("26","Manufacture of computer, electronic and optical products","C","Manufacturing"),
    ("27","Manufacture of electrical equipment","C","Manufacturing"),
    ("28","Manufacture of machinery and equipment","C","Manufacturing"),
    ("29","Manufacture of motor vehicles, trailers and semi-trailers","C","Manufacturing"),
    ("30","Manufacture of other transport equipment","C","Manufacturing"),
    ("31","Manufacture of furniture","C","Manufacturing"),
    ("32","Other manufacturing","C","Manufacturing"),
    ("33","Repair and installation of machinery and equipment","C","Manufacturing"),
    ("35","Electricity, gas, steam and air conditioning supply","D","Electricity, Gas, Steam and Air Conditioning Supply"),
    ("36","Water collection, treatment and supply","E","Water Supply; Sewerage, Waste Management and Remediation Activities"),
    ("37","Sewerage","E","Water Supply; Sewerage, Waste Management and Remediation Activities"),
    ("38","Waste collection, treatment and disposal activities","E","Water Supply; Sewerage, Waste Management and Remediation Activities"),
    ("39","Remediation activities and other waste management services","E","Water Supply; Sewerage, Waste Management and Remediation Activities"),
    ("41","Construction of buildings","F","Construction"),
    ("42","Civil engineering","F","Construction"),
    ("43","Specialised construction activities","F","Construction"),
    ("45","Wholesale and retail trade and repair of motor vehicles","G","Wholesale and Retail Trade; Repair of Motor Vehicles"),
    ("46","Wholesale trade, except of motor vehicles and motorcycles","G","Wholesale and Retail Trade; Repair of Motor Vehicles"),
    ("47","Retail trade, except of motor vehicles and motorcycles","G","Wholesale and Retail Trade; Repair of Motor Vehicles"),
    ("49","Land transport and transport via pipelines","H","Transportation and Storage"),
    ("50","Water transport","H","Transportation and Storage"),
    ("51","Air transport","H","Transportation and Storage"),
    ("52","Warehousing and support activities for transportation","H","Transportation and Storage"),
    ("53","Postal and courier activities","H","Transportation and Storage"),
    ("55","Accommodation","I","Accommodation and Food Service Activities"),
    ("56","Food and beverage service activities","I","Accommodation and Food Service Activities"),
    ("58","Publishing activities","J","Information and Communication"),
    ("59","Motion picture, video and television programme production","J","Information and Communication"),
    ("60","Programming and broadcasting activities","J","Information and Communication"),
    ("61","Telecommunications","J","Information and Communication"),
    ("62","Computer programming, consultancy and related activities","J","Information and Communication"),
    ("63","Information service activities","J","Information and Communication"),
    ("64","Financial service activities","K","Financial and Insurance Activities"),
    ("65","Insurance, reinsurance and pension funding","K","Financial and Insurance Activities"),
    ("66","Activities auxiliary to financial services and insurance","K","Financial and Insurance Activities"),
    ("68","Real estate activities","L","Real Estate Activities"),
    ("69","Legal and accounting activities","M","Professional, Scientific and Technical Activities"),
    ("70","Activities of head offices; management consultancy","M","Professional, Scientific and Technical Activities"),
    ("71","Architectural and engineering activities; technical testing","M","Professional, Scientific and Technical Activities"),
    ("72","Scientific research and development","M","Professional, Scientific and Technical Activities"),
    ("73","Advertising and market research","M","Professional, Scientific and Technical Activities"),
    ("74","Other professional, scientific and technical activities","M","Professional, Scientific and Technical Activities"),
    ("75","Veterinary activities","M","Professional, Scientific and Technical Activities"),
    ("77","Rental and leasing activities","N","Administrative and Support Service Activities"),
    ("78","Employment activities","N","Administrative and Support Service Activities"),
    ("79","Travel agency and tour operator activities","N","Administrative and Support Service Activities"),
    ("80","Security and investigation activities","N","Administrative and Support Service Activities"),
    ("81","Services to buildings and landscape activities","N","Administrative and Support Service Activities"),
    ("82","Office administrative and business support activities","N","Administrative and Support Service Activities"),
    ("84","Public administration and defence; compulsory social security","O","Public Administration and Defence; Compulsory Social Security"),
    ("85","Education","P","Education"),
    ("86","Human health activities","Q","Human Health and Social Work Activities"),
    ("87","Residential care activities","Q","Human Health and Social Work Activities"),
    ("88","Social work activities without accommodation","Q","Human Health and Social Work Activities"),
    ("90","Creative, arts and entertainment activities","R","Arts, Entertainment and Recreation"),
    ("91","Libraries, archives, museums and other cultural activities","R","Arts, Entertainment and Recreation"),
    ("92","Gambling and betting activities","R","Arts, Entertainment and Recreation"),
    ("93","Sports activities and amusement and recreation activities","R","Arts, Entertainment and Recreation"),
    ("94","Activities of membership organisations","S","Other Service Activities"),
    ("95","Repair of computers and personal and household goods","S","Other Service Activities"),
    ("96","Other personal service activities","S","Other Service Activities"),
    ("97","Activities of households as employers of domestic personnel","T","Activities of Households as Employers"),
    ("98","Undifferentiated goods/services-producing activities of private households","T","Activities of Households as Employers"),
    ("99","Activities of extraterritorial organisations and bodies","U","Activities of Extraterritorial Organisations and Bodies"),
]

DIVISION_BY_CODE = {
    d[0]: {"code": d[0], "name": d[1], "section": d[2], "section_name": d[3]}
    for d in ISIC_DIVISIONS
}

KEYWORD_MAP = {
    "health": "86", "medical": "86", "hospital": "86", "clinical": "86",
    "patient": "86", "disease": "86", "cancer": "86", "hiv": "86",
    "covid": "86", "pandemic": "86", "mental health": "86", "nursing": "86",
    "therapy": "86", "vaccination": "86", "chronic": "86",
    "pharmaceutical": "21", "drug": "21",
    "disability": "88", "welfare": "88", "social work": "88",
    "care": "87", "elderly": "87", "nursing home": "87",
    "education": "85", "school": "85", "university": "85", "student": "85",
    "teacher": "85", "learning": "85", "curriculum": "85", "classroom": "85",
    "higher education": "85", "pedagogy": "85", "teaching": "85",
    "qualitative": "72", "interview": "72", "survey": "72", "research": "72",
    "sociology": "72", "anthropology": "72", "ethnography": "72",
    "focus group": "72", "narrative": "72", "phenomenology": "72",
    "grounded theory": "72", "case study": "72", "fieldwork": "72",
    "policy": "84", "government": "84", "political": "84", "democracy": "84",
    "election": "84", "parliament": "84", "public administration": "84",
    "legislation": "84", "governance": "84", "military": "84",
    "migration": "84", "immigrant": "84", "refugee": "84",
    "law": "69", "legal": "69", "court": "69", "justice": "69",
    "crime": "69", "criminal": "69", "rights": "69", "regulation": "69",
    "economic": "64", "finance": "64", "bank": "64", "market": "64",
    "income": "64", "poverty": "88", "inequality": "88",
    "employment": "78", "labour": "78", "work": "78", "job": "78",
    "unemployment": "78",
    "climate": "72", "environment": "72", "energy": "35", "renewable": "35",
    "geothermal": "35", "water": "36", "agriculture": "01", "farming": "01",
    "forest": "02", "biodiversity": "72", "sustainability": "72",
    "software": "62", "technology": "62", "digital": "63", "internet": "63",
    "algorithm": "62", "artificial intelligence": "62", "data science": "62",
    "machine learning": "62", "computer": "62",
    "gender": "72", "women": "72", "feminist": "72", "race": "72",
    "ethnicity": "72", "lgbtq": "72", "discrimination": "84",
    "culture": "90", "art": "90", "music": "90", "literature": "91",
    "museum": "91", "heritage": "91", "media": "60", "journalism": "60",
    "family": "72", "children": "88", "youth": "88", "fertility": "86",
    "birth": "86", "population": "72", "demographic": "72",
    "management": "70", "organisation": "70", "leadership": "70",
    "innovation": "72", "entrepreneurship": "70", "startup": "70",
    "corporate": "70", "strategy": "70",
    "housing": "68", "urban": "84", "city": "84", "community": "84",
    "food": "10", "nutrition": "86",
    "transport": "49", "mobility": "49",
}


def label(code):
    d = DIVISION_BY_CODE.get(str(code))
    if not d:
        return "UNKNOWN"
    return f"{d['code']} \u2013 {d['name']}"
